version: '3.8'

services:
  django:
    build: 
      context: .
      dockerfile: ./Dockerfile.django
    container_name: django
    command: ./docker-entrypoint.sh
    volumes:
      - .:/usr/src/app/
      - .db_data/db.sqlite3:/db.sqlite3
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  celery:
    build: 
      context: .
      dockerfile: ./Dockerfile.celery
    command: ./celery-entrypoint.sh
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    volumes:
      - .:/usr/src/app/
    depends_on:
      - django
      - redis

  redis:
    image: redis:alpine